ServiceName: payments-failure-intelligence-api
SourceConfiguration:
  ImageRepository:
    ImageIdentifier: <account>.dkr.ecr.<region>.amazonaws.com/payments-failure-intelligence-api:latest
    ImageRepositoryType: ECR
    ImageConfiguration:
      Port: "8000"
      RuntimeEnvironmentVariables:
        APP_ENV: production
        APP_HOST: 0.0.0.0
        APP_PORT: "8000"
        DATABASE_URL: <rds-connection-string>
        REDIS_URL: <elasticache-redis-url>
        REDIS_QUEUE_NAME: payment-batch-jobs
        MLFLOW_TRACKING_URI: <optional-mlflow-url>
        MODEL_ARTIFACT_PATH: /app/artifacts/model_bundle.joblib
        MODEL_VERSION: deployed-v1
        USE_FEAST_ONLINE_LOOKUP: "false"
AutoScalingConfigurationArn: <app-runner-auto-scaling-config-arn>
HealthCheckConfiguration:
  Path: /health
  Protocol: HTTP
