JOB_STATUS_QUEUED = "queued"
JOB_STATUS_PROCESSING = "processing"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_FAILED = "failed"

JOB_STATUSES = {
    JOB_STATUS_QUEUED,
    JOB_STATUS_PROCESSING,
    JOB_STATUS_COMPLETED,
    JOB_STATUS_FAILED,
}

RECOMMENDATION_RETRY_ONCE = "retry_once"
RECOMMENDATION_FAILOVER_TERMINAL = "failover_terminal"
RECOMMENDATION_ESCALATE_GATEWAY = "escalate_gateway"
RECOMMENDATION_MANUAL_REVIEW = "manual_review"
RECOMMENDATION_NO_ACTION = "no_action"

DEFAULT_MODEL_STAGE = "Production"
DEFAULT_MODEL_ALIAS = "champion"
DEFAULT_REDIS_QUEUE_NAME = "payment-batch-jobs"

